nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.0.0.cjs
npmScopes:
  studiokaiji:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: ${GITHUB_REGISTRY_TOKEN:-fallback}