nodeLinker: node-modules

npmScopes:
  studiokaiji:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_REGISTRY_TOKEN:-fallback}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
