name = "workers"
main = "src/index.ts"
compatibility_date = "2022-11-10"
workers_dev = true

tsconfig = "./tsconfig.json"

[env.local.vars]
FIREBASE_AUTH_EMULATOR_HOST = "127.0.0.1:9099" # Specify if using emulator.
PUBLIC_JWK_CACHE_KEY = "public-jwk-cache-key" # Cache key to store and get public jwk.
CHAIN_RPC_ENDPOINTS=["127.0.0.1:8545"]
CHAIN_ID="31337"

[env.local]
kv_namespaces = [
  { binding = "PUBLIC_JWK_CACHE_KV", id="b4a473dd2e158379b4d43d958d0548a3", preview_id = "b4a473dd2e158379b4d43d958d0548a3" },
  { binding = "SUBSCRIPTION_CACHE_KV", id="c9664447722d4a71b4d91d13132d343", preview_id = "c9664447722d4a71b4d91d13132d343" }
]

[env.production.vars]
PUBLIC_JWK_CACHE_KEY = "public-jwk-cache-key" # Cache key to store and get public jwk.
CHAIN_RPC_ENDPOINTS=[
  "https://polygon-mainnet.g.alchemy.com/v2/bVUlXIXBMbSORNOTC-tqrAfpDVYTtuWj",
  "https://rpc.ankr.com/polygon",
  "https://thecreator.infura-ipfs.io"
]

[env.production]
kv_namespaces = [
  { binding = "PUBLIC_JWK_CACHE_KV", id = "b4a473dd2e158379b4d43d958d0548a3" },
  { binding = "SUBSCRIPTION_CACHE_KV", id = "c9664447722d4a71b4d91d13132d343" }
]